<a href="https://colab.research.google.com/github/jmwangi20/12-factor-agents/blob/main/00_introduction_to_pytorch_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version)

AttributeError: module 'torch' has no attribute '__version'

## Introduction to Tensors

###Creating Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

In [ ]:
#Get the tensor information
scalar.ndim

In [ ]:
#get the tensor back
scalar.item()

In [ ]:
#Easiest way to remember a vector is that a vector for vectors count the number of square brackets
#Vectors ussually have a magnitude and direction

vector = torch.vector([3,7])
vector

In [ ]:
#check the number of dimensions =>one pair of closing square brackets
vector.ndim

In [ ]:
#check the shape of the tensor
vector.shape

In [ ]:
# creating matrices with tensors
matrix = torch.tensor([7,8],
                     [4,4])
matrix

In [ ]:
# check the number of dimensions
matrix.ndim


In [ ]:
#shape of the matrix
matrix.shape

In [ ]:
#Tensor
Tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
Tensor

In [ ]:
#check the number of dimensions
Tensor.ndim


In [ ]:
#check the shape of the matrix
Tensor.shape

## Random Tensors

### Why random tensors?
Random tensors are very important in the neural networks because of the way they learn.They ussually start with random numbers and adjust gradually as they learn.

```start with random numbers -> look at the data -> update the random numbers -> look at the data```

In [3]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3391, 0.2353, 0.0946, 0.6025],
        [0.7520, 0.7327, 0.4416, 0.8759],
        [0.8374, 0.9684, 0.9310, 0.5342]])

In [4]:
#check the dimension of the random tensor
random_tensor.ndim

2

In [5]:
#create an image size tensor

random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [7]:
 #create tensors of zeros and ones
 zeros = torch.zeros(size=(3,4))
 zeros.dtype,zeros.ndim,zeros.shape

(torch.float32, 2, torch.Size([3, 4]))

In [8]:
#create tensors of ones
ones = torch.tensor(size = (3,4))
ones.dtype,ones.ndim,ones.shape

TypeError: tensor() missing 1 required positional arguments: "data"

### Creating a range of tensors and tensorls-like

In [9]:
#use torch.arange to create range tensors
zero_to_ten = torch.arange(start=0,end=11,step=1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# tensors_like create tensors of the same shape as of the like to tensor
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes
**Note:** Tensors datatypes is one of the big errors you`ll run into with pytorch and Deeplearning.

  1. Tensors not in the right datatype

  2. Tensors not in the right shape

  3. Tensors not in the right device



In [12]:
# float_32_tensors
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor


tensor([3., 6., 9.])

In [13]:
# Convert float32 into float16 datatype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor



tensor([3., 6., 9.], dtype=torch.float16)

In [15]:
#Getting tensor attributes

some_tensor = torch.rand(3,4)
some_tensor


tensor([[0.3690, 0.2436, 0.1860, 0.8458],
        [0.6240, 0.4323, 0.4175, 0.8475],
        [0.2783, 0.9996, 0.5705, 0.9414]])

In [16]:
#print the tensor attributes
print(some_tensor)
print(f"Data type of the tensor:{some_tensor.dtype}")
print(f"shape of the tensor:{some_tensor.shape}")
print(f"Device the tensor is on:{some_tensor.device}")

tensor([[0.3690, 0.2436, 0.1860, 0.8458],
        [0.6240, 0.4323, 0.4175, 0.8475],
        [0.2783, 0.9996, 0.5705, 0.9414]])
Data type of the tensor:torch.float32
shape of the tensor:torch.Size([3, 4])
Device the tensor is on:cpu


### Manipulating tensors

Tensor operations include:

  1. Addition
  2. Subtraction
  3. Multiplication(Element-wise)
  4. Division
  5. Matrix multplication




In [18]:
#create a tensor and add 10
tensor=torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [19]:
  #tensor multiplication
tensor * 10


tensor([10, 20, 30])

In [20]:
#tensor subtraction
tensor-10

tensor([-9, -8, -7])

In [21]:
torch.add(tensor,12)

tensor([13, 14, 15])